baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Tobia's log"

theme = 'PaperMod'
[params]
  # enable search globally
  fuse = true

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "This is subtitle"
imageUrl = "https://www.altrasoluzione.com/images/blog/siti-per-scaricare-immagini-gratis-legalmente/immagini-gratis-big.jpg"
imageTitle = "<title of image as alt>"


imageWidth = 120
imageHeight = 120


  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/AleCava01"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/alecavalieri/"

[[params.socialIcons]]
name = "Instagram"
url = "<link2>"

# -------------------
# Navigation Menu
# -------------------
[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  url = "/archive/"
  weight = 2

  [[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 3


[outputs]
home = ["HTML", "RSS", "JSON"]
